tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "teamookla/speedtest"
brew "asitop"
brew "borgbackup"
brew "btop"
brew "pcre2"
brew "croc"
brew "curl"
brew "exiftool"
brew "openjpeg"
brew "ffmpeg"
brew "git"
brew "gnu-tar"
brew "hugo"
brew "iperf3"
brew "lazydocker"
brew "mailsy"
brew "mas"
brew "neofetch"
brew "openssh"
brew "rsync"
brew "smartmontools"
brew "switchaudio-osx"
brew "tmux"
brew "tree"
brew "video-compare"
brew "vim"
brew "wimlib"
brew "yt-dlp"
brew "zsh"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "teamookla/speedtest/speedtest"
cask "1password"
cask "adobe-creative-cloud"
cask "alt-tab"
cask "appcleaner"
cask "arc"
cask "balenaetcher"
cask "battle-net"
cask "blender"
cask "carbon-copy-cloner"
cask "citrix-workspace"
cask "cryptomator"
cask "direqual"
cask "discord"
cask "easyfind"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "epic-games"
cask "ff-works"
cask "git-credential-manager"
cask "google-chrome"
cask "google-drive"
cask "gpg-suite-no-mail"
cask "iina"
cask "ilok-license-manager"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "keyboard-maestro"
cask "kitty"
cask "logi-options-plus"
cask "loopback"
cask "lunar"
cask "macwhisper"
cask "maxon"
cask "mediathekview"
cask "microsoft-auto-update"
cask "microsoft-office-businesspro"
cask "microsoft-remote-desktop"
cask "minecraft"
cask "mullvadvpn"
cask "nvidia-geforce-now"
cask "obs"
cask "obsidian"
cask "onyx"
cask "opencore-patcher"
cask "openzfs"
cask "paragon-ntfs"
cask "parsec"
cask "raycast"
cask "resilio-sync"
cask "rode-central"
cask "rsyncui"
cask "spitfire-audio"
cask "spotify"
cask "steam"
cask "syncthing"
cask "tailscale"
cask "teamviewer"
cask "threema"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "vorta"
cask "wacom-tablet"
cask "waves-central"
cask "yubico-yubikey-manager"
mas "1Blocker", id: 1365531024
mas "1Password for Safari", id: 1569813296
mas "AJA System Test Lite", id: 1092006274
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "AutoMounter", id: 1160435653
mas "CapCut", id: 1500855883
mas "Hush", id: 1544743900
mas "Magnet", id: 441258766
mas "MediaInfo", id: 510620098
mas "Podlive", id: 1210411572
mas "TestFlight", id: 899247664
mas "WireGuard", id: 1451685025
vscode "esbenp.prettier-vscode"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.powershell"
